# Generated by Django 3.1.13 on 2022-01-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(help_text='Which features did you like, any improvement to be done...', null=True)),
                ('opinion', models.CharField(choices=[('Very Helpful', 'Very Helpful'), ('Educative', 'Educative'), ('Not Helpful', 'Not Helpful')], max_length=100)),
            ],
        ),
    ]
