# Generated by Django 3.1.13 on 2022-01-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
