# Generated by Django 3.1.13 on 2022-01-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_comment_date_reported'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_reported',
            new_name='date_created',
        ),
    ]
